logger:
   dir: /install_apps/intelliJ_bak/os/libra
   level: INFO

application:
  name: libra

#zookeeper
zk:
  url: zk1.dev.pajkdc.com:2181,zk2.dev.pajkdc.com:2181,zk3.dev.pajkdc.com:2181

#database
db:
  libra:
    url: jdbc:mysql://10.255.132.19:3306/test
    username: jkshop
    password: hVsXZa7fpbwv7fpd2QHDp5KkEndS9jyu6E+s827Vxn/Dy10XdeBJDACwTKvBj0+MJ3Ib7MgId+2Xm/pxWc5dSQ==
